export const PROFILE_ID_REQUIRED = 'PROFILE_ID_REQUIRED';
export const SHARE_LINK_NOT_FOUND = 'SHARE_LINK_NOT_FOUND';
export const SHARE_LINK_EXPIRED_OR_REVOKED = 'SHARE_LINK_EXPIRED_OR_REVOKED';
export const EXPIRY_MUST_BE_FUTURE = 'EXPIRY_MUST_BE_FUTURE';
export const INVALID_EXPIRES_IN_DAYS = 'INVALID_EXPIRES_IN_DAYS';
